logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: DEBUG
    tech.qpmatrix.airbnbclone: DEBUG
spring:
  profiles:
    active: dev
  application:
    name: airbnb-clone-server
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: Hikari
      auto-commit: false
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: airbnb_clone
  liquibase:
    contexts: dev
    change-log: classpath:db/changelog/master.xml
    default-schema: airbnb_clone
    enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
server:
  port: 8080
  servlet:
    context-path: /api/v1/
okta:
  oauth2:
    issuer: https://dev-rv06if8o5anakwyw.eu.auth0.com/
    client-id: ${AUTH0_CLIENT_ID}
    client-secret: ${AUTH0_CLIENT_SECRET}
application:
  auth0:
    role-landlord-id: rol_P9NpjDaykRFdk0fs